In [203]:
import pandas as pd

df = pd.read_csv("adult24.csv", na_values=["", " ", "-", "..", ":", "ukjent", "unknown"])
df = df[(df["SCHCURENR_A"] == 1) & (df["AGEP_A"].between(18, 29))]
df_lykke = df[["RATCAT_A", "FDSCAT4_A", "HOUSECOST_A", "HYPEV_A", "ASEV_A", "ARTHEV_A", "DIBEV_A"]]

In [204]:
df_lykke.head()

     RATCAT_A  FDSCAT4_A  HOUSECOST_A  HYPEV_A  ASEV_A  ARTHEV_A  DIBEV_A
27         14          1            2        2       2         2        2
54         12          1            1        2       1         2        2
57          5          1            2        2       2         2        2
67         14          1            2        2       1         2        2
101         6          1            2        2       2         2        2

In [205]:
df_lykke.nunique()

RATCAT_A       14
FDSCAT4_A       5
HOUSECOST_A     5
HYPEV_A         2
ASEV_A          3
ARTHEV_A        3
DIBEV_A         2
dtype: int64

In [206]:
df_lykke["RATCAT_A"].value_counts()

14    196
1     101
8      99
9      88
10     77
3      76
5      74
7      70
11     63
2      53
12     53
13     51
4      46
6      38
Name: RATCAT_A, dtype: int64

In [207]:
#"Ingen dårlige verdier ifølge Frequency Codebook"

In [208]:
df_lykke["FDSCAT4_A"].value_counts()

1    890
2     90
3     59
4     42
8      4
Name: FDSCAT4_A, dtype: int64

In [209]:
#"4 dårlige verdier ifølge frequency codebook"

In [210]:
df_lykke["HOUSECOST_A"].value_counts()

2    997
1     77
9      6
8      3
7      2
Name: HOUSECOST_A, dtype: int64

In [211]:
#"11 dårlige verdier"

In [212]:
df_lykke["HYPEV_A"].value_counts()

2    1037
1      48
Name: HYPEV_A, dtype: int64

In [213]:
#"Ingen feil verdier"

In [214]:
df_lykke["ASEV_A"].value_counts()

2    876
1    208
9      1
Name: ASEV_A, dtype: int64

In [215]:
#"1 dårlig verdi"

In [216]:
df_lykke["ARTHEV_A"].value_counts()

2    1062
1      22
9       1
Name: ARTHEV_A, dtype: int64

In [217]:
#1 dårlig verdi

In [218]:
df_lykke["DIBEV_A"].value_counts()

2    1081
1       4
Name: DIBEV_A, dtype: int64

In [219]:
#"Ingen dårlige verdier"

In [220]:
import numpy as np

bad_values = ["FDSCAT4_A", "HOUSECOST_A", "HYPEV_A", "ASEV_A", "ARTHEV_A", "DIBEV_A"]
yes_no = ["HOUSECOST_A", "HYPEV_A", "ASEV_A", "ARTHEV_A", "DIBEV_A"]

df_lykke[bad_values] = df_lykke[bad_values].replace({7: np.nan, 8: np.nan, 9: np.nan})
df_lykke[yes_no] = df_lykke[yes_no].replace({1: "YES", 2: "NO"})

df_lykke = df_lykke.rename(columns={
    "RATCAT_A": "family_income",
    "FDSCAT4_A": "food_security",
    "HOUSECOST_A": "housing_cost",
    "HYPEV_A": "high_blpressure",
    "ASEV_A": "had_asthma",
    "ARTHEV_A": "had_arthritis",
    "DIBEV_A": "had_diabetes"
})

df_lykke = df_lykke.reset_index(drop=True)

print(df_lykke)

      family_income  food_security housing_cost high_blpressure had_asthma  \
0                14            1.0           NO              NO         NO
1                12            1.0          YES              NO        YES
2                 5            1.0           NO              NO         NO
3                14            1.0           NO              NO        YES
4                 6            1.0           NO              NO         NO
...             ...            ...          ...             ...        ...
1080              8            1.0           NO              NO         NO
1081              1            1.0           NO              NO         NO
1082              2            1.0           NO              NO         NO
1083             13            1.0           NO              NO         NO
1084             13            1.0           NO              NO        YES

     had_arthritis had_diabetes
0               NO           NO
1               NO           NO
2               NO           NO
3               NO           NO
4               NO           NO
...            ...          ...
1080            NO           NO
1081            NO           NO
1082            NO           NO
1083            NO           NO
1084            NO           NO

[1085 rows x 7 columns]

C:\Users\lykke\anaconda3\lib\site-packages\pandas\core\frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [221]:
df_lykke.head()

,family_income,food_security,housing_cost,high_blpressure,had_asthma,had_arthritis,had_diabetes
0,14,1.0,NO,NO,NO,NO,NO
1,12,1.0,YES,NO,YES,NO,NO
2,5,1.0,NO,NO,NO,NO,NO
3,14,1.0,NO,NO,YES,NO,NO
4,6,1.0,NO,NO,NO,NO,NO

In [222]:
df_lykke.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1085 entries, 0 to 1084
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   family_income    1085 non-null   int64
 1   food_security    1081 non-null   float64
 2   housing_cost     1074 non-null   object
 3   high_blpressure  1085 non-null   object
 4   had_asthma       1084 non-null   object
 5   had_arthritis    1084 non-null   object
 6   had_diabetes     1085 non-null   object
dtypes: float64(1), int64(1), object(5)
memory usage: 59.5+ KB

In [223]:
df_lykke.isna().sum()

family_income       0
food_security       4
housing_cost       11
high_blpressure     0
had_asthma          1
had_arthritis       1
had_diabetes        0
dtype: int64

In [224]:
df_lykke["housing_cost"].value_counts(dropna=False)

NO     997
YES     77
NaN     11
Name: housing_cost, dtype: int64

In [225]:
def food_security(value):
    if value == 1:
        return "High"
    elif value == 2:
        return "Marginal"
    elif value == 3:
        return "Low"
    elif value == 4:
        return "Very Low"
    else: 
        return np.nan

df_lykke_fsl = df_lykke.copy()    

df_lykke_fsl["food_security_level"] = df_lykke_fsl["food_security"].map(food_security)
df_lykke_fsl.head()

,family_income,food_security,housing_cost,high_blpressure,had_asthma,had_arthritis,had_diabetes,food_security_level
0,14,1.0,NO,NO,NO,NO,NO,High
1,12,1.0,YES,NO,YES,NO,NO,High
2,5,1.0,NO,NO,NO,NO,NO,High
3,14,1.0,NO,NO,YES,NO,NO,High
4,6,1.0,NO,NO,NO,NO,NO,High

In [226]:
#Dette kan også gjøres hvor jeg legger den nye kolonnen ved siden av food_security kolonnen

In [228]:
df_lykke_test = df_lykke.copy()

df_lykke_test["food_security"] = df_lykke_test["food_security"].replace({1.0: "High", 2.0: "Marginal", 3.0: "Low", 4.0: "Very low"})

df_lykke_test.head()

,family_income,food_security,housing_cost,high_blpressure,had_asthma,had_arthritis,had_diabetes
0,14,High,NO,NO,NO,NO,NO
1,12,High,YES,NO,YES,NO,NO
2,5,High,NO,NO,NO,NO,NO
3,14,High,NO,NO,YES,NO,NO
4,6,High,NO,NO,NO,NO,NO

In [229]:
#Dette er et annet forslag, hvor de originale verdiene til food_security byttes ut med mer lesbar tekst, i dette tilfellet; high, marginal, low, very low